#!/bin/sh

# 운영체제 확인
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    ;;
  'Darwin') 
    OS='Mac'
    ;;
  'CYGWIN'* | 'MINGW32'* | 'MSYS'* | 'MINGW'*)
    OS='Windows'
    ;;
  *)
    OS='Unknown'
    ;;
esac

if [ "$OS" = "Linux" ] || [ "$OS" = "Mac" ]; then
    echo "Post Checkout Hook"
elif [ "$OS" = "Windows" ]; then
    powershell.exe -ExecutionPolicy Bypass -File hooks/post_update_version.ps1
else
    
    exit 1
fi
