#!/bin/sh

# 운영체제 확인
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    ;;
  'Darwin') 
    OS='Mac'
    ;;
  'CYGWIN'* | 'MINGW32'* | 'MSYS'* | 'MINGW'*)
    OS='Windows'
    ;;
  *)
    OS='Unknown'
    ;;
esac

if [ "$OS" = "Linux" ] || [ "$OS" = "Mac" ]; then
    # Linux 또는 macOS용 스크립트
    VERSION=$(git describe --tags --always)
    COMMIT_HASH=$(git rev-parse --short HEAD)
    BUILD_DATE=$(git show -s --format=%cs HEAD)

    echo "Version: $VERSION" > version.info
    echo "Commit Hash: $COMMIT_HASH" >> version.info
    echo "Build Date: $BUILD_DATE" >> version.info

    git add version.info

elif [ "$OS" = "Windows" ]; then
    powershell.exe -ExecutionPolicy Bypass -File hooks/update_version.ps1
else
    
    exit 1
fi
