#!/bin/sh

# 운영체제 확인
OS="`uname`"
case $OS in
  'Linux')
    OS='Linux'
    ;;
  'Darwin') 
    OS='Mac'
    ;;
  'CYGWIN'* | 'MINGW32'* | 'MSYS'* | 'MINGW'*)
    OS='Windows'
    ;;
  *)
    OS='Unknown'
    ;;
esac

if [ "$OS" = "Linux" ] || [ "$OS" = "Mac" ]; then
    # Linux 또는 macOS용 스크립트
    VERSION=$(git describe --tags --always)
    COMMIT_HASH=$(git rev-parse --short HEAD)
    BUILD_DATE=$(date)

    echo "Version: $VERSION" > version.info
    echo "Commit Hash: $COMMIT_HASH" >> version.info
    echo "Build Date: $BUILD_DATE" >> version.info

    git add version.info

elif [ "$OS" = "Windows" ]; then
    # Windows용 스크립트 (PowerShell 호출)
    powershell.exe -ExecutionPolicy Bypass -Command "
    \$VERSION = git describe --tags --always;
    \$COMMIT_HASH = git rev-parse --short HEAD;
    \$BUILD_DATE = Get-Date -Format 'yyyy-MM-ddTHH:mm:ss';
    'Version: \$VERSION' | Out-File -FilePath version.info;
    'Commit Hash: \$COMMIT_HASH' | Out-File -FilePath version.info -Append;
    'Build Date: \$BUILD_DATE' | Out-File -FilePath version.info -Append;
    git add version.info
    "
else
    echo "Unknown operating system: $OS"
    exit 1
fi
